Repository Varying-Vagrant-Vagrants/custom-site-template, pull requests merged in 2019-10, with the labels that each got.

#27 Set strict script execution for site provisioners
  provision/vvv-init.sh
Labels: enhancement, help wanted

#28 Force install of specific WordPress version
  .gitignore
  provision/vvv-init.sh
Labels: enhancement, help wanted

#29 Theme installation support
  README.md
  provision/vvv-init.sh
Labels: enhancement

#25 Check if the site is installed, and then attempt to restore from backup
  provision/vvv-init.sh
Labels: bug, enhancement
